version: "3.7"

services:
  frontend:
    build: st
    ports:
      - 8501:8501
    networks: 
      dn: 
        aliases: 
          - frontend.docker
    depends_on:
      - backend

  backend:
    build: api
    ports:
      - 8000:8000
    networks: 
      dn: 
        aliases: 
          - backend.docker

networks:
  dn:
    external: false